name: abadinursery
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  flutter_switch: ^0.3.2
  http: ^1.2.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.4
  intl: ^0.19.0
  loading_animation_widget: ^1.1.0+5
  mysql1: ^0.20.0
  overlay_support: ^2.1.0
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  timeline_tile: ^2.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

  assets:
    - assets/images/default_avatar.jpg
    - assets/images/
    - assets/images/logo/circularcustom.png